src/java/com/ibucket/managedbeans/GalleryBean.java
package com.ibucket.managedbeans;

import com.ibucket.persistence.Gallery;
import com.ibucket.persistence.Picture;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.PhaseId;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

/**
 * 
 * Bean für Gallery
 * @version 0.9b
 * @author Robert Werth, Roland Hantel, Marko Schulze, Florian Vollmann
 */
@ManagedBean(name = "galleryBean")
@RequestScoped
public class GalleryBean {

    @ManagedProperty(value = "#{loginBean}")
    private LoginBean loginBean;
    private String galleryName;
    private List<Gallery> galleries;
    private Map<Integer, List<String>> galleryNumbers = new HashMap<>();
    private Map<Integer, List<String>> galleryPictureDescriptions = new HashMap<>();

    /**
     * Creates a new instance of GalleryBean
     */
    public GalleryBean() {
    }
    
    /**
     * Initialisiert Klassenvariablen
     */
    @PostConstruct
    public void init() {
        galleryName = "";
        galleries = null;
        galleryNumbers = new HashMap<>();
        galleryPictureDescriptions = new HashMap<>();
        if (!loginBean.isNotLoggedIn()) {
            galleries = loginBean.usr.getAllGalleries();
            for (Gallery g : galleries) {
                List<Picture> pictures = new ArrayList<>(g.getPictureCollection());
                Collections.sort(pictures, new Comparator<Picture>() {
                    @Override
                    public int compare(Picture p1, Picture p2) {
                        return p1.getNr()-p2.getNr();
                    }
                });
                List<String> pictureDescriptions = new ArrayList<>();
                List<String> numbers = new ArrayList<>();                           
                for (Picture p : pictures) {
                    numbers.add(Integer.toString(p.getPictureId()));
                    pictureDescriptions.add(p.getDescription());
                }
                galleryPictureDescriptions.put(g.getGalleryId(), pictureDescriptions);
                galleryNumbers.put(g.getGalleryId(), numbers);
            }
        }
    }
    
    public String getLink(String id) {
        return FacesContext.getCurrentInstance().getExternalContext().getRequestContextPath() + "/javax.faces.resource/dynamiccontent.properties.xhtml?ln=primefaces&pfdrid=VyNz3i0uOYnQ9Uc0DFN1sg2e%2B2MD5MrJ&imageID=" + id + "&pfdrid_c=true";
    }
    
    public void setLoginBean(LoginBean loginBean) {
        this.loginBean = loginBean;
    }

    public String getGalleryName() {
        return galleryName;
    }

    public void setGalleryName(String galleryName) {
        this.galleryName = galleryName;
    }

    /**
     * Erstellt eine neue Galerie.
     * @return Navigation-String "gallery" um auf die gallery.xhtml weiterzuleiten
     */
    public String createGallery() {
        loginBean.usr.createGallery(galleryName);
        loginBean.refresh();
        init();
        return "gallery";
    }
    
    public List<Gallery> getGalleries() {
        return galleries;
    }

    public Map<Integer, List<String>> getGalleryNumbers() {
        return galleryNumbers;
    }   

    public Map<Integer, List<String>> getGalleryPictureDescriptions() {
        return galleryPictureDescriptions;
    }
    
    /**
     * Löscht eine Gallerie
     * @param galleryId Id der zu löschenden Galerie
     * @return Navigation-String "gallery" für die Weiterleitung zur gallery.xhtml
     */
    public String deleteGallery(int galleryId) {
        loginBean.usr.deleteGallery(galleryId);
        loginBean.refresh();
        init();
        return "gallery";
    }

    /**
     * Erstellt eine Gallerie
     * @param galleries 
     */
    public void setGalleries(List<Gallery> galleries) {
        this.galleries = galleries;
    }
    
    public String getDescription(String i) {        
        Picture picture = loginBean.usr.ownsPicture(i);
        
        return picture.getDescription();
    }    
    
    /**
     * Holt die Bilder einer Gallerie
     * @return StreamedContent-Objekt des Bildes, wenn das Bild öffentlich ist oder 
     * dem Nutzer gehört
     * @throws FileNotFoundException
     * @throws URISyntaxException 
     */
    public StreamedContent getImage() throws FileNotFoundException, URISyntaxException {
        if (FacesContext.getCurrentInstance().getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
            return new DefaultStreamedContent();
        }
        else {
            String i = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("imageID");
            StreamedContent stream = null;
            Picture picture = loginBean.anon.isPicturePublic(Integer.parseInt(i));
            if (picture != null) {               
                stream = readFile(picture);
            }
            else {
                picture = loginBean.usr.ownsPicture(i);
                if (picture != null) {
                    stream = readFile(picture);
                }
                else {
                    stream = new DefaultStreamedContent();
                }
            }     
            return stream;
        }
    }
    
    /**
     * Streamt ein Bild
     * @param picture Datenbankobjekt des Bildes
     * @return Bild als StreamedContent-Objekt oder leeres StreamedContent-Objekt, wenn das Bild nicht gefunden wurde.
     */
    private StreamedContent readFile(Picture picture) {
        try {
            String filename = Integer.toString(picture.getFilename()) + "." + picture.getFiletype();
            File pictureFile = new File("../pictures/" + filename); 
            return new DefaultStreamedContent(new FileInputStream(pictureFile), "image/" + picture.getFiletype().toLowerCase(), filename);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ImageBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return new DefaultStreamedContent();
    }
    
    /**
     * Listener, der auf die gallery.xhtml weiterleitet, wenn der Optionsdialog geschlossen wird.
     * @throws IOException 
     */
    public void dialogReturnListener() throws IOException {
        FacesContext.getCurrentInstance().getExternalContext().redirect("gallery.xhtml");
    }
}

src/java/com/ibucket/managedbeans/LoginBean.java
package com.ibucket.managedbeans;

import com.ibucket.businesslayer.AnonUser;
import com.ibucket.businesslayer.AuthUser;
import javax.faces.bean.SessionScoped;
import java.io.Serializable;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;

/**
 * 
 * Bean für Loginform, beinhaltet Sessiondaten
 * @version 0.9b
 * @author Robert Werth, Roland Hantel, Marko Schulze, Florian Vollmann
 */
@ManagedBean(name = "loginBean")
@SessionScoped
public class LoginBean implements Serializable {
    
    // Anonyme Userfunktionen
    AnonUser anon;
    String logon;
    String password;
    
    /**
     * Angemeldeter Nutzer samt Funktionen
     **/
    AuthUser usr;

    /**
     * Initieren einer neuen Instanz
     */
    public LoginBean()
    {
        anon = new AnonUser();
        usr = null;
    }
    
    /**
     * Check ob Sessionuser angemldet ist
     * @return true wenn nicht Angemeldet
     */
    public boolean isNotLoggedIn()
    {
        boolean var = usr == null;
        return var;
    }
    
    /**
     * Anmelden mit gegeben Daten vom Webinterface
     * @return 
     */
    public String loginAction()
    {
        usr = anon.login(logon, password);
        if (usr == null)
        {
            FacesContext ctx = FacesContext.getCurrentInstance();
            ctx.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR,"Login fehlgeschlagen!","Nutzername oder Passwort falsch."));
        } else {
            logon = usr.getLogon();
        }
        return "index";
    }
    
    /**
     * Abmelden des Benutzers
     * @return Startseite
     */
    public String logoutAction()
    {
        this.usr.logout();
        this.usr =null;
        this.logon = "";
        this.password ="";
        return "index";

    }
    
    
    public void setLogon(String logon) {
        this.logon = logon;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getLogon() {
        return logon;
    }

    public String getPassword() {
        return null;
    }
    /**
     * Prüft ob das Bild dem ANgemldeten Nutzer gehört
     * @param imgId
     * @return true wenn Angemldeter Benutzer der Besitzer ist
     */
    public boolean ownsPicture(String imgId) {
        return usr.ownsPicture(imgId) != null;
    }
    
    /**
     * Prüft ob Galerie dem Nutzer gehört
     * @param galleryId
     * @return true wenn Angemldeter Benutzer der Besitzer der Galerie ist
     */
    public boolean ownsGallery(String galleryId) {
        return usr.ownsGallery(Integer.parseInt(galleryId)) != null;
    }
    
    /**
     * Auffrischen der Benutzerdaten der Session
     */
    public void refresh() {
        usr = anon.login(logon, password);
    }
}

src/java/com/ibucket/managedbeans/SGalleryBean.java
package com.ibucket.managedbeans;

import com.ibucket.persistence.Gallery;
import com.ibucket.persistence.Picture;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.context.FacesContext;
import javax.faces.event.PhaseId;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

/**
 * 
 * Bean für einzele Gallerie
 * @version 0.9b
 * @author Robert Werth, Roland Hantel, Marko Schulze, Florian Vollmann
 */
@ManagedBean(name = "sGalleryBean")
@RequestScoped
public class SGalleryBean {

    @ManagedProperty(value = "#{loginBean}")
    private LoginBean loginBean;
    private String galleryName;
    private String galleryId;
    private Gallery gallery;
    private List<String> galleryNumbers;
    private Map<String, String> imageDescriptions;
    
    /**
     * Creates a new instance of SGalleryBean
     */
    public SGalleryBean() {

    }
    
    /**
     * prüft Zugriffsrechte und initialisiert die Objecte
     */
    @PostConstruct
    private void init() {
        galleryId = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("galleryID");    
        if (galleryId != null) {
            gallery = loginBean.anon.isGalleryPublic(Integer.parseInt(galleryId));
            if (gallery == null && !loginBean.isNotLoggedIn()) {
                List<Gallery> galleries = loginBean.usr.getAllGalleries();
                for (Gallery g : galleries) {
                    if (Objects.equals(g.getGalleryId(), Integer.valueOf(galleryId))) {
                        gallery = g;
                        break;
                    }
                }
            }
            if (gallery != null) {
                galleryNumbers = new ArrayList<>();
                imageDescriptions = new HashMap<>();
                List<Picture> list = new ArrayList<>(gallery.getPictureCollection());
                Collections.sort(list, new Comparator<Picture>() {
                    @Override
                    public int compare(Picture p1, Picture p2) {
                        return p1.getNr()-p2.getNr();
                    }
                });
                for (Picture p : list) {
                    galleryNumbers.add(Integer.toString(p.getPictureId()));
                    imageDescriptions.put(Integer.toString(p.getPictureId()), p.getDescription());
                }
                galleryName = gallery.getName();
            }
        }
    }

    public void setLoginBean(LoginBean loginBean) {
        this.loginBean = loginBean;
    }

    public String getDescription() {
    return gallery.getDescription();
}
    
    public String getImageDescription(String id) {
        return imageDescriptions.get(id);
    }
    
    public String getGalleryName() {
        return galleryName;
    }

    public void setGalleryName(String galleryName) {
        this.galleryName = galleryName;
    }

    public List<String> getGalleryNumbers() {
        return galleryNumbers;
    }

    public void setGalleryNumbers(List<String> galleryNumbers) {
        this.galleryNumbers = galleryNumbers;
    }

    public String getGalleryId() {
        return galleryId;
    }

    public void setGalleryId(String galleryId) {
        this.galleryId = galleryId;
    }

    public Gallery getGallery() {
        return gallery;
    }

    public void setGallery(Gallery gallery) {
        this.gallery = gallery;
    }

    /**
     * Stream ein Bild
     * @param picture
     * @return 
     */
    private StreamedContent readFile(Picture picture) {
        try {
            String filename = Integer.toString(picture.getFilename()) + "." + picture.getFiletype();
            File pictureFile = new File("../pictures/" + filename); 
            return new DefaultStreamedContent(new FileInputStream(pictureFile), "image/" + picture.getFiletype().toLowerCase(), filename);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ImageBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return new DefaultStreamedContent();
    }
    
    /**
     * holt ein Bild
     * @return Bild
     */
    public StreamedContent getImage() {
        if (FacesContext.getCurrentInstance().getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
            return new DefaultStreamedContent();
        }
        else {
            String imageId = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("imageID");
            Picture p = loginBean.anon.isPicturePublic(Integer.parseInt(imageId));
            if (p == null) {
                p = loginBean.usr.ownsPicture(imageId);
            }
            return readFile(p);
        }
    }
    
    /**
     * prüft ob eine Gallerie sichtbar ist
     * @return boolean
     */
    public boolean canShow() {
        return gallery != null;
    }
}

web/gallery.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html" xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:body>
        <ui:composition template="./template.xhtml">
            <ui:define name="content">
                <p:panel rendered="#{loginBean.notLoggedIn}">
                    <h3>Fehler, du bist nicht angemeldet!</h3>
                </p:panel>
                
                <p:panel id="panelGallery" header="Galerie" rendered="#{!loginBean.notLoggedIn}" styleClass="panel" >                    
                    <h:form acceptcharset="ISO-8859-1">
                        <p:outputLabel for="galleryName" value="Galeriename:"/>
                        <p:inputText id="galleryName" value="#{galleryBean.galleryName}" required="true"/>
                        <p:commandButton action="#{galleryBean.createGallery()}" value="Erstellen" ajax="false">
                            <f:param value="2" name="i"/>
                        </p:commandButton>
                    </h:form>                    
                    
                    <p:outputPanel rendered="#{galleryBean.galleries.isEmpty()}">
                        <br/>
                        Es wurden noch keine Galerien angelegt!
                    </p:outputPanel>

                    <ui:repeat var="gal" varStatus="status" value="#{galleryBean.galleries}" rendered="#{!galleryBean.galleries.isEmpty()}">
                        <p:outputPanel deferred="true" deferredMode="visible">
                            <br/>
                            <b>#{gal.name}</b>
                            <p:outputPanel rendered="#{gal.description != null and !gal.description.isEmpty()}">
                                <br/>
                                #{gal.description}
                            </p:outputPanel>
                            <br/>
                            <p:outputPanel rendered="#{galleryBean.galleryNumbers.get(gal.galleryId).isEmpty()}" >                            
                                In dieser Galerie befinden sich keine Bilder!
                                <br/><br/>
                            </p:outputPanel>
                            <br/>
                            <p:galleria var="i" value="#{galleryBean.galleryNumbers.get(gal.galleryId)}" panelWidth="800" panelHeight="600" showCaption="true" rendered="#{!galleryBean.galleryNumbers.get(gal.galleryId).isEmpty()}">
                                <p:graphicImage value="#{galleryBean.image}" cache="true" alt="#{galleryBean.getDescription(i)}" title="" styleClass="content" style="display: block; max-width: 800px; max-height: 600px; width: auto; height: auto; margin: auto">
                                    <f:param name="imageID" value="#{i}"/>
                                </p:graphicImage>
                            </p:galleria>

                            <h:form acceptcharset="ISO-8859-1">
                                <p:commandButton value="Optionen" icon="ui-icon-gear" actionListener="#{galleryConfigBean.viewConfig(gal.galleryId)}">
                                    <f:param name="galleryID" value="#{gal.galleryId}"/>
                                    <p:ajax event="dialogReturn" listener="#{galleryBean.dialogReturnListener}" />
                                </p:commandButton>
                                <p:commandButton icon="ui-icon-trash" value="Löschen" action="#{galleryBean.deleteGallery(gal.galleryId)}" ajax="false"/>
                                <p:button value="Zur Galerie" outcome="sgallery.xhtml?galleryID=#{gal.galleryId}" icon="ui-icon-link" target="_blank"/>
                            </h:form>    
                        </p:outputPanel>
                    </ui:repeat>

                </p:panel>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

web/galleryconfig.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <h:panelGroup rendered="#{!loginBean.notLoggedIn}">
            <title>Galerie #{galleryConfigBean.galleryName}</title>
        </h:panelGroup>
        <h:panelGroup rendered="#{loginBean.notLoggedIn}">
            <title>Fehler</title>
        </h:panelGroup>
    </h:head>
    <h:body>
        <div class="ui-widget">
            <h:form acceptcharset="ISO-8859-1" rendered="#{loginBean.ownsGallery(galleryConfigBean.galleryId)}">
                Galeriename<br/>
                <p:inputText value="#{galleryConfigBean.galleryName}" style="width: 372px"/><br/>
                Beschreibung <br/>
                <p:inputTextarea value="#{galleryConfigBean.description}" rows="5" cols="41"/><br/>
                Status <br/>
                <span style="color: red; font-size: 0.7em">Bitte beachten: Durch veröffentlichen der Galerie werden gleichzeitig alle zugeordneten Bilder veröffentlicht!</span><br/>
                <p:selectOneRadio value="#{galleryConfigBean.status}">
                    <f:selectItem itemValue="#{galleryConfigBean.statusPrivate}" itemLabel="Privat"/>
                    <f:selectItem itemValue="#{galleryConfigBean.statusPublic}" itemLabel="Öffentlich"/>
                </p:selectOneRadio><br/>

                <p:commandButton value="Speichern" action="#{galleryConfigBean.save()}">
                    <f:param name="galleryID" value="#{galleryConfigBean.galleryId}"/>
                </p:commandButton>
            </h:form>
            <p:panel rendered="#{!loginBean.ownsGallery(galleryConfigBean.galleryId)}">
                Du bist nicht der Besitzer dieser Galerie!
            </p:panel>
        </div>
    </h:body>
</html>


web/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html" xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui">

    <!--<h:body>-->
        <ui:composition template="./template.xhtml">
            <ui:define name="content">
                <h1>Willkommen bei</h1>                    
                <br/>               
                <p:graphicImage library="img" value="img/2.png"/>
                <br/>
                <p:outputLabel rendered="#{loginBean.notLoggedIn}">
                    Du bist noch nicht registriert?
                    Dann registriere dich sofort kostenlos! 
                    <p:button href="register.xhtml" value="Registrieren"/>
                </p:outputLabel>
            </ui:define>
        </ui:composition>
    <!--</h:body>-->
</html>

web/pictureconfig.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>        
        <h:panelGroup rendered="#{!loginBean.notLoggedIn}">
            <title>Bild ##{imageConfigBean.imageId}</title>
        </h:panelGroup>
        <h:panelGroup rendered="#{loginBean.notLoggedIn}">
            <title>Fehler</title>
        </h:panelGroup>
    </h:head>
    <h:body>
        <div class="ui-widget">
            <h:form acceptcharset="ISO-8859-1" rendered="#{loginBean.ownsPicture(imageConfigBean.picture.pictureId.toString())}">
                Beschreibung <br/>
                <p:inputTextarea value="#{imageConfigBean.description}" rows="5" cols="41"/><br/>
                Status <br/>
                <span style="color: red; font-size: 0.7em">Bitte beachten: Bilder, die Teil einer öffentlichen Galerie sind, können nicht auf privat umgestellt werden!</span><br/>
                <p:selectOneRadio value="#{imageConfigBean.status}">
                    <f:selectItem itemValue="#{imageConfigBean.statusPrivate}" itemLabel="Privat"/>
                    <f:selectItem itemValue="#{imageConfigBean.statusPublic}" itemLabel="Öffentlich"/>
                </p:selectOneRadio><br/>
                Galerie<br/>
                <p:selectOneMenu value="#{imageConfigBean.gallery}" style="width: 372px">
                    <f:selectItem itemValue="0" itemLabel=""/>
                    <f:selectItems var="gal" value="#{imageConfigBean.galleries}" itemDescription="#{gal.description}" itemValue="#{gal.galleryId}" itemLabel="#{gal.name}"/>
                </p:selectOneMenu><br/>
                Position in der Galerie:<br/>
                <p:inputText value="#{imageConfigBean.nr}" type="number" /><br/>
                <p:commandButton value="Speichern" action="#{imageConfigBean.save()}">
                    <f:param name="imageID" value="#{imageConfigBean.imageId}"/>
                </p:commandButton>
            </h:form>
            <p:panel rendered="#{!loginBean.ownsPicture(imageConfigBean.picture.pictureId.toString())}">
                Du bist nicht der Besitzer dieses Bildes!
            </p:panel>
        </div>
    </h:body>
</html>


web/pictures.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html" xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <!--<h:body>-->
        <ui:composition template="./template.xhtml">
            <ui:define name="content">
                <p:panel rendered="#{loginBean.notLoggedIn}">
                    <h3>Fehler, du bist nicht angemeldet!</h3>
                </p:panel>  
                
                <p:panel rendered="#{!loginBean.notLoggedIn}" header="Meine Bilder">
                    <!--                Bilder              -->
                    <ul class="gallery">
                        <p:outputPanel rendered="#{imageBean.imageNumbers.isEmpty()}">
                            Es wurde noch keine Bilder hochgeladen!
                        </p:outputPanel>
                        <ui:repeat var="i" value="#{imageBean.imageNumbers}" rendered="#{!imageBean.imageNumbers.isEmpty()}">
                            <li>  
                                <p:outputPanel deferred="true" deferredMode="visible">
                                    <h:form acceptcharset="ISO-8859-1">
                                        <a href="#{imageBean.getLink(i)}" target="_blank">
                                            <p:graphicImage value="#{imageBean.thumbnail}" cache="true" styleClass="content">
                                                <f:param name="imageID" value="#{i}"/>
                                            </p:graphicImage>
                                        </a>
                                        <p:commandButton value="Optionen" actionListener="#{imageConfigBean.viewConfig(i)}">
                                            <f:param name="imageID" value="#{i}"/>
                                        </p:commandButton>
                                        <p:commandButton value="Löschen" action="#{imageBean.deleteImage(i)}" ajax="false"/>
                                    </h:form>
                                </p:outputPanel>
                            </li>
                        </ui:repeat>
                    </ul>
                </p:panel>
            </ui:define>
        </ui:composition>
    <!--</h:body>-->
</html>

web/upload.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html" xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui">

    <h:body>
        <ui:composition template="./template.xhtml">
            <ui:define name="content">
                <p:panel rendered="#{loginBean.notLoggedIn}">
                    <h3>Fehler, du bist nicht angemeldet!</h3>
                </p:panel>
                
                <p:panel id="panelUpload" header="Bilder Upload" rendered="#{!loginBean.notLoggedIn}" styleClass="panel">
                    <h:form enctype="multipart/form-data">
                        <p:fileUpload multiple="true" sizeLimit="10485760" fileUploadListener="#{fileUploadBean.upload}" allowTypes="/(\.|\/)(gif|jpg|jpeg|png|PNG|GIF|JPG|JPEG)$/" label="Hinzufügen" uploadLabel="Upload" cancelLabel="Abbrechen" previewWidth="0"/>
                    </h:form>
                </p:panel>
            </ui:define>
        </ui:composition>
    </h:body>
</html>
